### ISSUE TITLE
Clear add activity form after the successful submission

### ISSUE THREAD

**Issue by selva-thayalan** [bored-funkies/weekly-hacks#2]
The form is not clearing automatically after submitting a new activity.

**Comment by Marigameo** [comment]
Fixed with this commit - https://github.com/bored-funkies/weekly-hacks/commit/61c1c2b579c5835cf74653388bc9a83080aa9d07

**Comment by Marigameo** [comment]
Verified in https://weekly-hacks.netlify.app/add-activity
